name: Daily lessons
on:
  schedule:
    - cron: '0 14 * * *' # <- Use UTC Time +0 , change your time here ( 14 is hour , 0 is minutes ) and use 24-hour format
  workflow_dispatch:

   
jobs:
  Manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Run DuoXPy
        run: python DuoXPy/DuoXPy.py
        env:
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          LESSONS: 10